import { createFileRoute } from "@tanstack/react-router";
import { Eye, Flag, Handshake, ShieldCheck } from "lucide-react";
import { EstimateBand, PageHero, SectionHeading } from "@/components/page-elements";
import aboutImage from "@/assets/dmr-about.jpg";

export const Route = createFileRoute("/about")({ head:()=>({meta:[{title:"About DMR | Excavating & Landscaping"},{name:"description",content:"Meet the experienced team and values behind DMR Excavating & Landscaping."},{property:"og:title",content:"About DMR Excavating & Landscaping"},{property:"og:description",content:"Experience, integrity and hard work from the ground up."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}), component: About });
function About(){return <><PageHero eyebrow="Our company" title="Built on work that speaks for itself." copy="DMR is an excavation and landscaping partner for homeowners, builders, farms and communities who expect the ground beneath every project to be right."/>
<section className="mx-auto grid max-w-7xl gap-12 px-5 py-24 lg:grid-cols-2 lg:px-8 lg:py-32"><div className="relative min-h-[480px] overflow-hidden"><img src={aboutImage} loading="lazy" alt="DMR excavation equipment preparing a landscaped property" width={1600} height={1056} className="absolute inset-0 h-full w-full object-cover"/><div className="absolute bottom-0 right-0 bg-primary p-7 text-primary-foreground"><p className="font-display text-5xl font-black">10+</p><p className="text-[10px] font-bold uppercase tracking-[.15em]">Years of field experience</p></div></div><div className="flex flex-col justify-center"><SectionHeading eyebrow="Our story" title="A reputation earned in the dirt."/><div className="mt-7 space-y-5 leading-7 text-muted-foreground"><p>DMR was built around a simple belief: difficult work should still feel straightforward for the customer. We combine hands-on experience, capable equipment and clear communication to remove uncertainty from demanding projects.</p><p>Our crew looks beyond the immediate task. Drainage, access, material movement, finish quality and the next phase all influence how we plan the work. The result is a site that performs as well as it looks.</p></div></div></section>
<section className="border-y border-border bg-surface px-5 py-24 lg:px-8"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Direction" title="Purpose in every pass."/><div className="mt-12 grid md:grid-cols-2"><article className="border border-border p-8 md:p-12"><Flag className="text-primary"/><h3 className="mt-10 text-4xl font-black uppercase">Mission</h3><p className="mt-4 leading-7 text-muted-foreground">To deliver dependable excavation and landscape construction with care, precision and an uncompromising standard of workmanship.</p></article><article className="border border-border p-8 md:p-12"><Eye className="text-primary"/><h3 className="mt-10 text-4xl font-black uppercase">Vision</h3><p className="mt-4 leading-7 text-muted-foreground">To be the first call for clients who value honest partnership, resilient sites and work built for the long haul.</p></article></div></div></section>
<section className="px-5 py-24 lg:px-8"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="What guides us" title="Straightforward values."/><div className="mt-12 grid gap-px bg-border md:grid-cols-3">{[{icon:ShieldCheck,title:"Own the outcome",copy:"We stand behind the quality, safety and finish of our work."},{icon:Handshake,title:"Respect the property",copy:"Every site is treated with care, clear access and organized cleanup."},{icon:Flag,title:"Do the hard part well",copy:"Preparation and precision define the work nobody should have to redo."}].map(({icon:Icon,title,copy})=><article key={title} className="bg-background p-8"><Icon className="text-primary"/><h3 className="mt-10 text-2xl font-black uppercase">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{copy}</p></article>)}</div></div></section><EstimateBand/></>}